save_window: 180
save_interval: 15

# wofs to preds
wofs_rel_path: "2019/20190520/0030/ENS_MEM_1"
wofs_file: "wrfwof_d01_2019-05-21_00:30:00"
loc_wofs: "/datadrive/wofs/"
datetime_format: "%Y-%m-%d_%H:%M:%S"
dir_preds: "/datadrive/wofs_preds/"
dir_patches: "/datadrive/wofs_patches/"
with_nans:
fields: "U WSPD10MAX W_UP_MAX"
loc_model: "/home/ggantos/tornado_jtti/lydia_scripts/models/initialrun_model8/initialrun_model8.h5"
file_trainset_stats: "/home/ggantos/tornado_jtti/lydia_scripts/training_metadata/3D_light/training_onehot_tor/training_metadata_ZH_only.nc"
write: 4
dry_run:
