name: tf_tornado
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - tensorflow
  - keras-tuner
  - xarray
  - jupyterlab
  - netcdf4
  - wrf-python
  - metpy
  - tqdm
  - dask
  - pip
  - pytest
  - pyyaml
  - pyproj
  - py3nvml
  - pydot
  - seaborn
